add integration tests
NVIDIA-Merlin/Merlin pull request #310
Opened 2022-05-13 05:18 UTC by radekosmulski

This is still a WIP, only adding it here in case anyone would like to see/comment on these changes!

implements #214

2022-05-18 21:06 UTC, radekosmulski commented
Finally! 🥳

This is now passing on ngc, works okay with a 32GB GPU. Both the unit and integration tests run okay.

@bschifferer this is good to go AFAICT 🙂 

```
From https://github.com/NVIDIA-Merlin/Merlin
 * [new ref]         refs/pull/310/head -> add_integration_test
Switched to branch 'add_integration_test'
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.1, pluggy-1.0.0
rootdir: /Merlin
plugins: anyio-3.6.1
collected 2 items

tests/examples/unit/test_building_deploying_multi_stage_RecSys.py ..     [100%]

======================== 2 passed in 163.13s (0:02:43) =========================
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.1, pluggy-1.0.0
rootdir: /Merlin
plugins: anyio-3.6.1
collected 2 items

tests/examples/integration/test_building_deploying_multi_stage_RecSys.py . [ 50%]
.                                                                        [100%]

======================== 2 passed in 2963.12s (0:49:23) ========================
```

2022-05-26 12:35 UTC, bschifferer requested changes
Should we keep it as one unittest? because they depend on each other?

2022-05-26 19:11 UTC, radekosmulski commented on tests/examples/unit/test_building_deploying_multi_stage_RecSys.py
> +def test_nb2(tb):
That's a good point! I didn't think of the dependency, you are right. Will revert to how it was before.

The problem I encountered which prompted this change was that now with running on much bigger data I was running out of GPU RAM when this was a single test. But maybe this was due to some other issue in the code at that time.

Will switch to this being a single test, rerun the code on a 32GB GPU on ngc and if there will be issues will see if I can shutdown the first NB or clear the state via some other means when running the 2nd one.

2022-05-27 09:33 UTC, radekosmulski commented
Finally got this to pass on an ngc instance with a 32 GPU 🙂 

The integration test is formatted rather weirdly, but that is because regardless of what I tried, I was getting an OOM error. If the first notebook is used in the decorator, no matter what I tried, the state was retained inside the function after the execution of `tb1` finishes. The only way I managed to free up GPU memory was through the use of the context manager.

2022-06-21 13:36 UTC, bschifferer commented
rerun tests

2022-06-21 16:53 UTC, rnyak approved these changes

2022-06-22 12:01 UTC, bschifferer approved these changes

2022-06-22 12:02 UTC, bschifferer commented
rerun tests

2022-06-23 07:10 UTC, bschifferer commented
rerun tests

2022-06-23 08:07 UTC, bschifferer commented
rerun tests

2022-06-27 07:36 UTC, bschifferer commented
rerun tests

2022-06-29 16:23 UTC, bschifferer commented
rerun tests

2022-07-11 07:02 UTC, bschifferer commented
rerun tests

2022-07-11 15:21 UTC, jperez999 requested changes

2022-07-11 15:21 UTC, jperez999 commented on examples/Building-and-deploying-multi-stage-RecSys/01-Building-Recommender-Systems-with-Merlin.ipynb
> +      "application/javascript": [
remove this change and the tests seem to work. I would replace this code box with a text box that just tells them the command to run.

2022-07-12 17:00 UTC, merged