Add sok tests in Merlin
NVIDIA-Merlin/Merlin pull request #335
Opened 2022-05-25 05:41 UTC by EmmaQiaoCh

* change dockerfile to build sok unit test;
* keep the source folder which has sok test scripts;
* add sok test in ci/test_container.sh

2022-05-25 23:57 UTC, benfred commented
This looks good to me - have you built the container and tested that all the tests pass @EmmaQiaoCh  ?

2022-05-26 00:11 UTC, jperez999 commented
The following line needs to be removed https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.tf#L116 and you need to figure out another way to get your package recognized. If you like that line in the dockerfile, anything you pip install after the ENV VAR is updated will fail, which is why we originally did https://github.com/NVIDIA-Merlin/Merlin/pull/317/. If you want to see an issue I hit, install jupyterlab and try to run... tensorboard will fail to load. Without the added path, it loads correctly.

2022-05-26 14:58 UTC, EmmaQiaoCh commented
> The following line needs to be removed https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/training/dockerfile.tf#L116 and you need to figure out another way to get your package recognized. If you keep that line in the dockerfile, anything you pip install after the ENV VAR is updated will fail, which is why we originally did #317. If you want to see an issue I hit, install jupyterlab and try to run... tensorboard plugin will fail to load. Without the added path, it loads correctly.

Hi Julio,
Thanks for your comments, I can reproduce the jupyterlab problem. I tried to downgrade setuptools to '59.4.0', sok installed normally and no ENV needs. And the following distributed_embeddings also installed successfully. But still met the tensorboard plugin load failure. It works on @benfred 's PR, but sok test failed, so we need more time to fix these problems.

2022-05-27 08:29 UTC, EmmaQiaoCh commented
I've removed env PYTHONPATH and change to use the pip to install SOK, Please review the code changes. Thanks
Please Note: these changes depends on https://github.com/NVIDIA-Merlin/HugeCTR/pull/317 and https://github.com/NVIDIA-Merlin/HugeCTR/pull/320

2022-06-09 04:19 UTC, benfred requested changes

2022-06-09 04:19 UTC, benfred commented on docker/training/dockerfile.tf
> +    PYTHONPATH=/usr/local/hugectr/lib:$PYTHONPATH \
```suggestion
```

2022-06-13 03:36 UTC, closed without merging