modify multi-stage deployment nbs and unit test  wrt recent changes in systems
NVIDIA-Merlin/Merlin pull request #618
Opened 2022-09-13 21:00 UTC by rnyak

2022-09-13 21:12 UTC, rnyak commented
@bschifferer do you mind to check the nbs and unit test at your end? unit test is failing for me. wondering if I am missing something? Thanks!

2022-09-14 13:34 UTC, jperez999 requested changes

2022-09-14 13:34 UTC, jperez999 commented on examples/Building-and-deploying-multi-stage-RecSys/02-Deploying-multi-stage-RecSys-with-Merlin-Systems.ipynb
> +    "# read in data for request\n",
This code should be injected in to the notebook, not part of the actual notebook. The user shouldn't grab this data from the parquet file. They should get the raw_user_id from part 1 notebook when exploring the users. This is necessary when we are creating synthetic data for unit/integration tests

2022-09-14 15:20 UTC, rnyak commented
closing bcs of conflicts, opening a new one.

2022-09-14 15:20 UTC, closed without merging